name: Test the Input Logic
on: 
  push: 
    branches: main

jobs:
  buildfile:
    - name: Build a file 
      run: echo This is a Input Artifact > uploadartifact
      
  TestDownload:
    uses: Dilipkumar1127/Download-Artifact/.github/workflows/DownloadArtifact.yml@main
    with:
    
      WorkingDirectory: '.'
      inputArtifactPath: 'Downloads'
      inputArtifactUploadName: 'uploadartifact'
      CompressArtifacts: false
