name: GitHub Actions Demo
on:
  workflow_call:
    inputs:
      CompressArtifacts:
        description: Whether to compress or not the Artifact
        type: boolean  
      outputArtifactUploadName:
         default: outputartifact
         type: string
      WorkingDirectory:
         default: '.'
         type: string
         description: specify start dir
      outputArtifactPath:
         description: path of Artifact
         type: string
      
jobs:
  CreateBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Create Dir 
        run: mkdir ${{inputs.outputArtifactPath}}
      - name: echoing to a file
        run: echo Hello World > ${{inputs.outputArtifactPath}}/${{inputs.outputArtifactUploadName}}
      
      - name: listing 
        run: ls -R 
        
      - name: working dir print
        run : pwd
      
#       - name: Create Dir 
#         run: mkdir ${{inputs.outputArtifactPath}}
      - name: Compressing Artifacts
        if: ${{ inputs.CompressArtifacts == true }}
        run: tar -cvf ${{ inputs.outputArtifactUploadName }}.tar ${{ inputs.WorkingDirectory}}/${{inputs.outputArtifactPath}}/
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: ${{ inputs.CompressArtifacts == true }}
        with:
          name: ${{inputs.outputArtifactUploadName}}.tar
          path: ${{inputs.WorkingDirectory }}/${{inputs.outputArtifactPath}}

#       - name: Compressing Artifacts
#         if: ${{ inputs.CompressArtifacts == true }}
#         run: tar -cvf ${{ inputs.outputArtifactUploadName }}.tar ${{ inputs.WorkingDirectory}}/${{inputs.outputArtifactPath}}/
        
# #       - name: Extract Artifact
# #         run: tar -xvf ${{ inputs.WorkingDirectory }}/${{ inputs.outputArtifactPath }}/${{ inputs.outputArtifactUploadName }}.tar -C ${{ inputs.WorkingDirectory }}/${{inputs.outputArtifactPath}}/
        
#       # - name: If Downloading is True
#       #   if: ${{ inputs.DownloadArtifact == true }}
#       #   run: tar -xvf ${{ inputs.ArtifactName }}.tar -C ${{inputs.WorkingDir}}/${{inputs.ArtifactPath}}
 
#       - name: Publish Compressed Artifact
#         uses: actions/upload-artifact@v3
#         if: ${{inputs.CompressArtifacts == true}}
#         # if: ${{ inputs.ArtifactName  }}
#         with:
#           name: ${{ inputs.outputArtifactUploadName }}.tar
#           path: ${{ inputs.WorkingDirectory }}/${{inputs.outputArtifactPath}}
#           retention-days: 5
          
#       - name: print path
#         run: ls -R
      
#       - name: Extract Artifact
#         if: ${{ inputs.CompressArtifacts == true }}
#         run: tar -xvf ${{ inputs.WorkingDirectory }}/${{ inputs.outputArtifactPath }}/${{ inputs.outputArtifactUploadName }}.tar -C ${{ inputs.WorkingDirectory }}/${{inputs.outputArtifactPath}}/
      
#       - name: Publish Artifact
#         uses: actions/upload-artifact@v3
#         if: ${{ ( inputs.outputArtifactPath ) && ( inputs.CompressArtifacts != true ) }}
#         # if: ${{ inputs.ArtifactPath }}
#         with:
#           name: ${{ inputs.outputArtifactUploadName }}
#           path: ${{ inputs.WorkingDirectory }}/${{inputs.outputArtifactPath}}/${{ inputs.outputArtifactUploadName }}
#           retention-days: 5
      
# #       - name: listing 
# #         run: ls -R
      
# #       - name: view Download
# #         run: ls -R && cat ${{ inputs.outputArtifactUploadName }}
