name: Test the Download Logic
on: 
  push: 
    branches: main

jobs:
  buildfile:
    runs-on: ubuntu-latest
    steps:
      - name: Build a file 
        run: echo This is a Input Artifact > uploadartifact
      
  TestDownload:
    uses: Dilipkumar1127/Download-Artifact/.github/workflows/MainWorkflow.yml.yml@main
    with:
    
      WorkingDirectory: '.'
      inputArtifactPath: 'Downloads'
      inputArtifactUploadName: 'uploadartifact'
      CompressArtifacts: false
