name: Test the Download Logic
on: 
  push: 
    branches: main
  
  workflow_dispatch:

jobs:
  buildfile:
    runs-on: ubuntu-latest
    steps:
      - name: Build a file 
        run: echo This is a Input Artifact > uploadartifact
      
  Download:
    uses: Dilipkumar1127/Download-Artifact/.github/workflows/MainWorkflow.yml@main
    with:
    
      WorkingDirectory: '.'
      inputArtifactPath: Downloads
      inputArtifactDownloadName: uploadartifact
      CompressArtifacts: false
