name: Test the Download
on: 
  push: 
    branches: main

jobs:
  TestDownload:
    uses: Dilipkumar1127/Download-Artifact/.github/workflows/DownloadArtifact.yml@main
    with:
    
      WorkingDirectory: '.'
      outputArtifactPath: 'Downloads'
      outputArtifactUploadName: 'uploadartifact'
      CompressArtifacts: true
      
  DownlaodArtifact:
      runs-on: ubuntu-latest
      needs: TestDownload
      steps: 
        - name: Download Artifact
          uses: actions/download-artifact@v2
          with:
            name: uploadartifact
            path: ./Downloads
      
        - name: List
          run: ls -R
        
        - name: Extract file 
          run: tar -xvf ./Downloads/uploadartifact.tar -C ./Downloads/

        - name: View the Download
          run: cat ./Downloads/uploadartifact



    
